Repository camaraproject/DeviceLocation, pull requests merged in 2024-07, with the labels that each got.

#202 Update the geofencing subscription models to align on CAMARA commonalities
  code/API_definitions/geofencing-subscriptions.yaml
Labels: correction

#217 Add `Authorization and authentication` in `info.description`
  code/API_definitions/geofencing-subscriptions.yaml
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
Labels: documentation, Fall24

#215 location-verification: Alignment of errors with Commonalities
  code/API_definitions/location-verification.yaml
Labels: Fall24

#189 Testing plan for location verification
  code/Test_definitions/location-verification.feature
Labels: Fall24

#221 location-retrieval: Alignment of errors with Commonalities
  code/API_definitions/location-retrieval.yaml
Labels: Fall24

#218 Update `maxAge`-behaviour for `/verify` & `/retrieve`
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
Labels: Fall24

#234 Add Readiness checklist for Geofencing-Subscriptions
  documentation/API_documentation/geofencing-subscriptions-API-Readiness-Checklist.md
Labels: subproject management

#238 Prepare release 1.1 for location-verification + README + CHANGELOG
  CHANGELOG.md
  README.md
  code/API_definitions/location-verification.yaml
  code/Test_definitions/location-verification.feature
Labels: subproject management, Fall24

#235 Prepare API location-retrieval version 0.3.0-rc.1
  code/API_definitions/location-retrieval.yaml
  documentation/API_documentation/location-retrieval-API-Readiness-Checklist.md
Labels: subproject management, Fall24

#243 Add Max(DT) to CODEOWNERS
  CODEOWNERS
Labels: subproject management

#241 Prepare release 1.1 for location-verification
  code/API_definitions/location-verification.yaml
  code/Test_definitions/location-verification.feature
Labels: Fall24

#242 geofencing: Add `SUBSCRIPTION_DELETED` as termination-reason
  code/API_definitions/geofencing-subscriptions.yaml
Labels: enhancement, Fall24

#223 geofencing: Alignment of errors with Commonalities
  code/API_definitions/geofencing-subscriptions.yaml
Labels: enhancement, Fall24

#245 Latest alignments and fixes for verification and retrieval
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
Labels: Fall24

#244 Prepare release 1.1 for geofencing-subscriptions
  code/API_definitions/geofencing-subscriptions.yaml
Labels: subproject management, Fall24

#246 Update externalDocs for rc.1
  code/API_definitions/geofencing-subscriptions.yaml
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
Labels: Fall24
