Repository camaraproject/DeviceLocation, pull requests merged in 2024-08, with the labels that each got.

#227 location-verification Create Location Verification User Story
  documentation/SupportingDocuments/Location_Verification_User_Story.md
Labels: Fall24

#251 Move User Story to API_documentation
  documentation/API_documentation/location-verification-User-Story.md
Labels: documentation, correction, Fall24

#224 Add handling when the requested geofence `area` cannot be covered
  code/API_definitions/geofencing-subscriptions.yaml
Labels: enhancement, Fall24, waitingForCommonalities

#181 Geofencing feature file
  code/Test_definitions/Geofencing.feature
Labels: Fall24

#248 Update location-verification-API-Readiness-Checklist.md
  documentation/API_documentation/location-verification-API-Readiness-Checklist.md
Labels: Fall24
