Repository camaraproject/DeviceLocation, pull requests merged in 2025-02, with the labels that each got.

#290 Pre-Release r2.1
  CHANGELOG.md
  README.md
  code/API_definitions/geofencing-subscriptions.yaml
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
  code/Test_definitions/geofencing-subscriptions.feature
  code/Test_definitions/location-retrieval.feature
  code/Test_definitions/location-verification.feature
  documentation/API_documentation/README.MD
  documentation/API_documentation/geofencing-subscriptions-API-Readiness-Checklist.md
  documentation/API_documentation/location-retrieval-API-Readiness-Checklist.md
  documentation/API_documentation/location-verification-API-Readiness-Checklist.md
  documentation/API_documentation/location-verification-User-Story.md
Labels: Spring25

#305 Reset version numbers to wip following r2.1
  code/API_definitions/geofencing-subscriptions.yaml
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
  code/Test_definitions/geofencing-subscriptions.feature
  code/Test_definitions/location-retrieval.feature
  code/Test_definitions/location-verification.feature
Labels: subproject management

#298 Set Device Object To Optional - According to API Design Guidelines
  code/API_definitions/geofencing-subscriptions.yaml
Labels: Spring25

#309 [geofencing-subscriptions]: Add "MISSING_IDENTIFIER" to the 422-error codes
  code/API_definitions/geofencing-subscriptions.yaml
  code/Test_definitions/geofencing-subscriptions.feature
Labels: correction, Spring25

#314 Enhance description UNKNOWN vs UNABLE_TO_FULFILL_MAX_AGE
  code/API_definitions/location-verification.yaml
Labels: Spring25

#310 Location Retrieval - Align Error Test
  code/API_definitions/location-retrieval.yaml
  code/Test_definitions/location-retrieval.feature
Labels: Spring25

#311 [geofencing-subscriptions]: Alignment on commonalities r2.3
  code/API_definitions/geofencing-subscriptions.yaml
Labels: correction, Spring25

#316 Location Retrieval - Remove unnecessary error 400
  code/API_definitions/location-retrieval.yaml
Labels: correction, Spring25
