Repository camaraproject/DeviceLocation, pull requests merged in 2025-07, with the labels that each got.

#357 [geofencing-subscriptions]: Define `id` to be mandatory in SubscriptionAsync
  code/API_definitions/geofencing-subscriptions.yaml
Labels: enhancement, Fall25

#351 Remove IDENTIFIER_MISMATCH error and associated test cases
  code/API_definitions/geofencing-subscriptions.yaml
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
  code/Test_definitions/geofencing-subscriptions.feature
  code/Test_definitions/location-retrieval.feature
  code/Test_definitions/location-verification.feature
Labels: correction, Fall25

#363 Missing security scheme notificationsBearerAuth in geo-fencing-subscription
  code/API_definitions/geofencing-subscriptions.yaml
Labels: Fall25

#360 Prepare r3.1
  CHANGELOG.md
  README.md
  code/API_definitions/geofencing-subscriptions.yaml
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
  code/Test_definitions/geofencing-subscriptions.feature
  code/Test_definitions/location-retrieval.feature
  code/Test_definitions/location-verification.feature
  documentation/API_documentation/geofencing-subscriptions-API-Readiness-Checklist.md
  documentation/API_documentation/location-retrieval-API-Readiness-Checklist.md
  documentation/API_documentation/location-verification-API-Readiness-Checklist.md
Labels: Fall25

#365 Reset versions in OAS and test plans to WIP
  code/API_definitions/geofencing-subscriptions.yaml
  code/API_definitions/location-retrieval.yaml
  code/API_definitions/location-verification.yaml
  code/Test_definitions/geofencing-subscriptions.feature
  code/Test_definitions/location-retrieval.feature
  code/Test_definitions/location-verification.feature
Labels: subproject management
